export type RedirectCode = 301 | 302 | 303 | 307 | 308;

export type HtaccessRedirectRule = {
  id: string;
  from: string;
  to: string;
  code: RedirectCode;
  /** Match query string exactly when true (uses QSA-friendly RewriteRule). */
  exactQuery?: boolean;
};

export type HtaccessOptions = {
  rules: HtaccessRedirectRule[];
  forceHttps?: boolean;
  forceWww?: boolean | "www" | "apex";
  /** Include RewriteEngine On (default true when any rewrite feature used). */
  enableRewriteEngine?: boolean;
};

export type HtaccessResult =
  | { ok: true; text: string }
  | { ok: false; error: string };

function normalizePath(path: string): string {
  const t = path.trim();
  if (!t) return "";
  if (/^https?:\/\//i.test(t)) return t;
  return t.startsWith("/") ? t : `/${t}`;
}

function escapeRewrite(path: string): string {
  // Escape regex metacharacters for RewriteRule pattern (path only)
  return path.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function buildHtaccessRedirects(
  options: HtaccessOptions,
): HtaccessResult {
  const rules = options.rules.filter(
    (r) => r.from.trim() && r.to.trim(),
  );

  const forceHttps = options.forceHttps === true;
  const wwwMode =
    options.forceWww === true || options.forceWww === "www"
      ? "www"
      : options.forceWww === "apex"
        ? "apex"
        : null;

  if (!rules.length && !forceHttps && !wwwMode) {
    return {
      ok: false,
      error: "Add at least one redirect, or enable HTTPS / www options.",
    };
  }

  if (rules.length > 50) {
    return { ok: false, error: "Limit is 50 redirect rules." };
  }

  for (const rule of rules) {
    const from = normalizePath(rule.from);
    const to = normalizePath(rule.to);
    if (!from || !to) {
      return { ok: false, error: "Each rule needs a from and to path/URL." };
    }
    if (from.includes(" ") || to.includes(" ")) {
      return { ok: false, error: "Paths/URLs cannot contain spaces." };
    }
  }

  const needsRewrite =
    forceHttps ||
    wwwMode !== null ||
    rules.some((r) => !/^https?:\/\//i.test(normalizePath(r.to)));

  const lines: string[] = [
    "# Generated by Forge — review before deploying",
  ];

  if (needsRewrite || options.enableRewriteEngine !== false) {
    lines.push("RewriteEngine On");
    lines.push("");
  }

  if (forceHttps) {
    lines.push("# Force HTTPS");
    lines.push("RewriteCond %{HTTPS} !=on");
    lines.push("RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
    lines.push("");
  }

  if (wwwMode === "www") {
    lines.push("# Force www");
    lines.push("RewriteCond %{HTTP_HOST} !^www\\. [NC]");
    lines.push(
      "RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]",
    );
    lines.push("");
  } else if (wwwMode === "apex") {
    lines.push("# Force apex (non-www)");
    lines.push("RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]");
    lines.push("RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]");
    lines.push("");
  }

  if (rules.length) {
    lines.push("# Redirects");
    for (const rule of rules) {
      const from = normalizePath(rule.from);
      const to = normalizePath(rule.to);
      const code = rule.code;

      if (/^https?:\/\//i.test(to)) {
        // External or absolute — use Redirect or RewriteRule
        if (from.includes("?") || rule.exactQuery) {
          const pathOnly = from.split("?")[0] || "/";
          const pattern = `^${escapeRewrite(pathOnly).replace(/^\//, "")}/?$`;
          lines.push(
            `RewriteRule ${pattern} ${to} [L,R=${code}]`,
          );
        } else {
          lines.push(`Redirect ${code} ${from} ${to}`);
        }
      } else {
        const pattern = `^${escapeRewrite(from).replace(/^\//, "")}/?$`;
        lines.push(`RewriteRule ${pattern} ${to} [L,R=${code}]`);
      }
    }
    lines.push("");
  }

  return { ok: true, text: lines.join("\n").replace(/\n{3,}/g, "\n\n") };
}
