export type RobotsUserAgentBlock = {
  id: string;
  userAgent: string;
  allow: string[];
  disallow: string[];
};

export type RobotsOptions = {
  blocks: RobotsUserAgentBlock[];
  sitemaps: string[];
  /** Optional crawl-delay (seconds) applied to each block when set. */
  crawlDelay?: number | null;
  /** Friendly comment header. */
  comment?: string;
};

export type RobotsResult =
  | { ok: true; text: string }
  | { ok: false; error: string };

function cleanLines(lines: string[]): string[] {
  return lines
    .map((l) => l.trim())
    .filter(Boolean)
    .filter((l) => !l.startsWith("#"));
}

export function parseRobotsPathLines(raw: string): string[] {
  return cleanLines(raw.split(/\r?\n/));
}

export function buildRobotsTxt(options: RobotsOptions): RobotsResult {
  const blocks = options.blocks.filter((b) => b.userAgent.trim());
  if (!blocks.length) {
    return { ok: false, error: "Add at least one User-agent block." };
  }

  for (const block of blocks) {
    if (!block.allow.length && !block.disallow.length) {
      return {
        ok: false,
        error: `User-agent ${block.userAgent}: add at least one Allow or Disallow path.`,
      };
    }
  }

  for (const sm of options.sitemaps) {
    const t = sm.trim();
    if (!t) continue;
    try {
      const u = new URL(t);
      if (u.protocol !== "http:" && u.protocol !== "https:") {
        return { ok: false, error: `Sitemap must be http(s): ${t}` };
      }
    } catch {
      return { ok: false, error: `Invalid sitemap URL: ${t}` };
    }
  }

  if (
    options.crawlDelay != null &&
    (!Number.isFinite(options.crawlDelay) || options.crawlDelay < 0)
  ) {
    return { ok: false, error: "Crawl-delay must be a non-negative number." };
  }

  const lines: string[] = [];
  if (options.comment?.trim()) {
    for (const c of options.comment.trim().split(/\r?\n/)) {
      lines.push(`# ${c}`);
    }
    lines.push("");
  } else {
    lines.push("# Generated by Forge");
    lines.push("");
  }

  for (const block of blocks) {
    lines.push(`User-agent: ${block.userAgent.trim()}`);
    for (const path of block.disallow) {
      lines.push(`Disallow: ${path}`);
    }
    for (const path of block.allow) {
      lines.push(`Allow: ${path}`);
    }
    if (options.crawlDelay != null && options.crawlDelay > 0) {
      lines.push(`Crawl-delay: ${options.crawlDelay}`);
    }
    lines.push("");
  }

  for (const sm of options.sitemaps) {
    const t = sm.trim();
    if (t) lines.push(`Sitemap: ${t}`);
  }

  if (lines[lines.length - 1] !== "") lines.push("");

  return { ok: true, text: lines.join("\n") };
}

export const DEFAULT_ROBOTS_BLOCKS: RobotsUserAgentBlock[] = [
  {
    id: "all",
    userAgent: "*",
    allow: ["/"],
    disallow: ["/admin/", "/api/"],
  },
];
